import type { Brief } from "./types";

export type Prospect = {
  id: string;
  status: "New" | "Contacted" | "In Pipeline" | "Passed";
  top_opportunity_tag: string;
  flagged_at: string;
  brief: Brief;
};

const make = (b: Partial<Brief> & Pick<Brief, "company_name" | "url" | "industry" | "platform" | "ai_readiness_score" | "llm_visibility_score" | "opportunity_tier" | "friction_opportunities" | "bd_opener">): Brief => ({
  platform_detail: "",
  tech_stack_tags: [],
  ai_readiness_rationale: "",
  llm_visibility_narrative: "",
  competitive_gaps: [],
  opportunity_rationale: "",
  ...b,
} as Brief);

export const SEEDED_PROSPECTS: Prospect[] = [
  {
    id: "1",
    status: "New",
    top_opportunity_tag: "Agentic AI",
    flagged_at: "Today at 3:14 AM",
    brief: make({
      company_name: "Midwest Regional Health System",
      url: "example-health.com",
      industry: "Healthcare",
      platform: "Epic + Custom .NET",
      platform_detail: "A tightly-coupled .NET stack on top of Epic creates integration friction but also a clear path to modernization with Codal's healthcare modernization playbook.",
      tech_stack_tags: ["Epic EHR", ".NET", "On-prem", "WebForms"],
      ai_readiness_score: 34,
      ai_readiness_rationale: "Heavy reliance on legacy .NET WebForms and minimal API surface limits near-term AI integration without modernization work.",
      llm_visibility_score: 18,
      llm_visibility_narrative: "When prompted for top regional health systems, this brand does not appear in Claude or ChatGPT responses. Cleveland Clinic, Mayo, and Northwestern dominate the responses. Closing this gap is a content + structured data play.",
      competitive_gaps: ["No conversational patient portal", "No AI-assisted scheduling", "No structured data for AI surfaces"],
      opportunity_tier: "L",
      opportunity_rationale: "Large modernization scope across patient access, clinical documentation, and communications.",
      bd_opener: "We noticed your patient portal runs on a tightly coupled .NET stack — the same architecture we modernized for a regional health system last year, cutting their onboarding time by 60%. Worth 20 minutes to show you what that looked like?",
      friction_opportunities: [
        { area: "Patient Access", friction: "Appointment scheduling requires phone-based coordination despite digital portal", ai_intervention: "Agentic scheduling AI with EHR integration handles booking, rescheduling, and waitlist management autonomously", codal_capability: "AI & Data", impact: "High" },
        { area: "Clinical Documentation", friction: "Staff manually transcribing physician notes into Epic", ai_intervention: "LLM-powered transcription with structured output piped directly into Epic fields", codal_capability: "Product Engineering", impact: "High" },
        { area: "Patient Communications", friction: "Discharge instructions and follow-up reminders are manual and inconsistent", ai_intervention: "Automated, personalized post-discharge agent that follows up based on condition and history", codal_capability: "AI & Data", impact: "Medium" },
      ],
    }),
  },
  {
    id: "2",
    status: "New",
    top_opportunity_tag: "Platform Migration",
    flagged_at: "Today at 3:14 AM",
    brief: make({
      company_name: "PrecisionParts Industrial Supply",
      url: "precisionparts-example.com",
      industry: "Manufacturing",
      platform: "Magento 1 (EOL)",
      platform_detail: "Magento 1 has been EOL since 2020 — security, payment compliance, and extension support are all degraded. BigCommerce B2B Edition is the standard migration path.",
      tech_stack_tags: ["Magento 1", "PHP", "MySQL", "jQuery"],
      ai_readiness_score: 22,
      ai_readiness_rationale: "Aging platform with no modern API surface; everything is a modernization gate.",
      llm_visibility_score: 11,
      llm_visibility_narrative: "Almost no presence in AI-driven B2B procurement answers. McMaster-Carr and Grainger dominate the responses.",
      competitive_gaps: ["No AI search/recommendations", "No quote-request automation", "No predictive reorder"],
      opportunity_tier: "L",
      opportunity_rationale: "Mandatory replatform plus full B2B commerce build.",
      bd_opener: "Your B2B catalog is running on Magento 1 — a platform that's been end-of-life since 2020. We just completed a very similar migration for a mid-size industrial distributor that took their order processing from 4 days to same-day. Happy to share the technical approach.",
      friction_opportunities: [
        { area: "Product Discovery", friction: "10,000+ SKU catalog with no faceted search or AI-powered recommendations", ai_intervention: "AI search with attribute-based filtering, cross-sell intelligence, and quote-request automation", codal_capability: "Unified Commerce", impact: "High" },
        { area: "Reorder Workflow", friction: "Repeat B2B orders require manual re-entry by account managers", ai_intervention: "Predictive reorder agent monitors consumption patterns and auto-generates POs for approval", codal_capability: "AI & Data", impact: "High" },
        { area: "Platform Stability", friction: "Magento 1 EOL creates security and compliance exposure", ai_intervention: "Migration to BigCommerce B2B Edition with custom ERP integration", codal_capability: "Product Engineering", impact: "High" },
      ],
    }),
  },
  {
    id: "3",
    status: "Contacted",
    top_opportunity_tag: "Commerce Modernization",
    flagged_at: "Yesterday at 3:22 AM",
    brief: make({
      company_name: "Summit Outdoor Brands",
      url: "summitoutdoor-example.com",
      industry: "Retail & Consumer Goods",
      platform: "Shopify Plus",
      platform_detail: "Shopify Plus is solid bones; Storefront API and Hydrogen open up a quick AI personalization path without re-platforming.",
      tech_stack_tags: ["Shopify Plus", "Liquid", "React (App)", "Klaviyo"],
      ai_readiness_score: 61,
      ai_readiness_rationale: "Modern commerce platform with extensibility, but the AI features are absent.",
      llm_visibility_score: 44,
      llm_visibility_narrative: "Moderate brand recognition but rarely surfaces in 'best outdoor gear' AI answers; REI and Patagonia dominate.",
      competitive_gaps: ["No visual search", "No size/fit AI", "Basic FAQ chatbot only"],
      opportunity_tier: "M",
      opportunity_rationale: "Targeted AI overlay engagement on a healthy platform.",
      bd_opener: "You're on Shopify Plus which gives you a solid foundation, but your product discovery experience is leaving conversion on the table — no visual search, no size/fit AI, and your chatbot is a basic FAQ bot. We built a fit-recommendation engine for an outdoor apparel brand last quarter that moved their conversion rate 18%. Worth a look?",
      friction_opportunities: [
        { area: "Product Discovery", friction: "Standard keyword search with no visual or attribute-based AI assistance", ai_intervention: "Visual search + AI-powered size/fit recommendation integrated with Shopify Storefront API", codal_capability: "Unified Commerce", impact: "High" },
        { area: "Customer Support", friction: "FAQ chatbot can't handle complex product questions or order modifications", ai_intervention: "RAG-powered support agent trained on product catalog and order data", codal_capability: "AI & Data", impact: "Medium" },
        { area: "Personalization", friction: "Homepage and collection pages show the same experience to all users", ai_intervention: "Behavioral personalization engine with real-time segment detection", codal_capability: "Product Engineering", impact: "Medium" },
      ],
    }),
  },
  {
    id: "4",
    status: "New",
    top_opportunity_tag: "Digital Experience Overhaul",
    flagged_at: "Today at 3:14 AM",
    brief: make({
      company_name: "Lakefront Community Bank",
      url: "lakefrontbank-example.com",
      industry: "Financial Services",
      platform: "Custom .NET + WordPress marketing site",
      platform_detail: "Split brochure-ware and core banking front-end; clear opportunity to unify and modernize with a compliance-aware AI layer.",
      tech_stack_tags: [".NET", "WordPress", "Fiserv core"],
      ai_readiness_score: 29,
      ai_readiness_rationale: "Heavy regulatory constraints plus legacy stack make AI features expensive without modernization.",
      llm_visibility_score: 15,
      llm_visibility_narrative: "Almost no presence in AI-driven 'community bank near me' or 'small business banking' queries.",
      competitive_gaps: ["No digital-only account opening", "No intelligent document processing", "No authenticated AI assistant"],
      opportunity_tier: "M",
      opportunity_rationale: "Mid-size regional engagement with clear ROI and high-trust expansion.",
      bd_opener: "Your digital account opening flow has 11 steps and requires a branch visit to complete — we helped Charles Schwab simplify a compliance-heavy digital flow for 1.8 million clients. That experience translates directly to community banking. Would you want to see how?",
      friction_opportunities: [
        { area: "Account Opening", friction: "Multi-step account opening with in-branch requirement for identity verification", ai_intervention: "AI-powered document verification and digital onboarding with FFIEC-compliant identity checks", codal_capability: "Product Engineering", impact: "High" },
        { area: "Loan Applications", friction: "PDF-based loan applications with 3-5 day processing time", ai_intervention: "Intelligent document processing with automated eligibility scoring and instant preliminary decisions", codal_capability: "AI & Data", impact: "High" },
        { area: "Customer Self-Service", friction: "Basic FAQ page; no conversational interface for account questions", ai_intervention: "Secure, authenticated AI assistant with access to account data via MCP integration", codal_capability: "AI & Data", impact: "Medium" },
      ],
    }),
  },
  {
    id: "5",
    status: "New",
    top_opportunity_tag: "Data Pipeline & AI",
    flagged_at: "Today at 3:14 AM",
    brief: make({
      company_name: "NovaBio Research Group",
      url: "novabio-example.com",
      industry: "Life Sciences & Pharmaceuticals",
      platform: "WordPress + Salesforce CRM",
      platform_detail: "Marketing site is WordPress; operational data lives in Salesforce + lab systems with no unifying data plane.",
      tech_stack_tags: ["WordPress", "Salesforce", "Veeva (likely)"],
      ai_readiness_score: 41,
      ai_readiness_rationale: "Decent CRM hygiene, but no data lakehouse or unified data plane for AI.",
      llm_visibility_score: 22,
      llm_visibility_narrative: "Limited visibility in AI-generated answers around their research areas.",
      competitive_gaps: ["No unified data lakehouse", "No internal RAG/research assistant", "No structured data for AI surfaces"],
      opportunity_tier: "M",
      opportunity_rationale: "Data platform engagement with downstream AI tooling.",
      bd_opener: "Your clinical trial data is almost certainly living in disconnected systems — we see it constantly in life sciences. We built a unified data layer for a pharma client last year that cut their trial reporting time from 6 weeks to 4 days. The architecture is replicable. Want to walk through it?",
      friction_opportunities: [
        { area: "Clinical Data", friction: "Trial data fragmented across Salesforce, spreadsheets, and lab systems", ai_intervention: "Unified lakehouse architecture with Databricks, real-time pipeline, and regulatory-compliant audit trail", codal_capability: "AI & Data", impact: "High" },
        { area: "Researcher Tools", friction: "Literature review and protocol drafting done entirely manually", ai_intervention: "RAG system trained on internal research corpus + PubMed for intelligent literature synthesis", codal_capability: "AI & Data", impact: "Medium" },
        { area: "Web Presence", friction: "WordPress site doesn't surface in AI-generated answers for key research areas", ai_intervention: "Structured data overhaul, schema markup, and content strategy for LLM search visibility", codal_capability: "Strategy", impact: "Medium" },
      ],
    }),
  },
  {
    id: "6",
    status: "In Pipeline",
    top_opportunity_tag: "Application Modernization",
    flagged_at: "3 days ago",
    brief: make({
      company_name: "CargoLink Logistics",
      url: "cargolink-example.com",
      industry: "Automotive & Logistics",
      platform: "Custom Java + legacy Oracle DB",
      platform_detail: "Java monolith on Oracle; containerization + event-driven architecture is the standard play here.",
      tech_stack_tags: ["Java", "Oracle", "WebLogic"],
      ai_readiness_score: 19,
      ai_readiness_rationale: "Monolithic architecture without APIs makes AI integration cost-prohibitive without modernization.",
      llm_visibility_score: 8,
      llm_visibility_narrative: "Effectively invisible in AI-driven freight and 3PL queries.",
      competitive_gaps: ["No real-time tracking API", "No predictive routing", "No carrier self-service onboarding"],
      opportunity_tier: "L",
      opportunity_rationale: "Major modernization with multi-phase rollout.",
      bd_opener: "A Java monolith on Oracle is a common starting point for logistics companies that grew fast and never had time to modernize. We're currently running a similar migration for a Shopify merchant logistics partner — the containerization approach we're using would apply directly to your architecture.",
      friction_opportunities: [
        { area: "Shipment Tracking", friction: "Real-time tracking requires customer service calls; no self-service visibility", ai_intervention: "Event-driven microservice architecture with real-time tracking API and proactive exception alerting", codal_capability: "Product Engineering", impact: "High" },
        { area: "Route Optimization", friction: "Manual dispatch process with no predictive routing", ai_intervention: "ML-powered routing engine with real-time traffic, weather, and capacity data", codal_capability: "AI & Data", impact: "High" },
        { area: "Carrier Integration", friction: "New carrier onboarding takes 4–6 weeks due to custom integration work", ai_intervention: "Composable integration layer with standardized carrier API adapters", codal_capability: "Product Engineering", impact: "Medium" },
      ],
    }),
  },
  {
    id: "7",
    status: "New",
    top_opportunity_tag: "Agentic AI",
    flagged_at: "Today at 3:14 AM",
    brief: make({
      company_name: "ClearPath Legal Tech",
      url: "clearpathlaw-example.com",
      industry: "Legal & Insurance",
      platform: "React + Node.js (custom)",
      platform_detail: "Modern stack — the engineering bar is there. What's missing is the AI/workflow automation layer.",
      tech_stack_tags: ["React", "Node.js", "Postgres", "AWS"],
      ai_readiness_score: 55,
      ai_readiness_rationale: "Modern stack and decent API surface — AI integration is mostly a product layer engagement.",
      llm_visibility_score: 31,
      llm_visibility_narrative: "Some presence in legaltech AI queries but overshadowed by Harvey, EvenUp, and CaseText.",
      competitive_gaps: ["No clause-extraction AI", "No conversational intake", "No internal legal-research RAG"],
      opportunity_tier: "M",
      opportunity_rationale: "Focused AI feature build on a healthy stack.",
      bd_opener: "You've got a solid React/Node foundation — the engineering is there. What's missing is the AI layer that would make your platform truly differentiated. We built a document exchange and workflow automation layer for a legal tech client last quarter that cut their claim processing time by 40%. Worth seeing the architecture?",
      friction_opportunities: [
        { area: "Document Review", friction: "Contract review and clause extraction done manually by associates", ai_intervention: "LLM-powered contract analysis with issue flagging, clause library matching, and redline suggestions", codal_capability: "AI & Data", impact: "High" },
        { area: "Client Intake", friction: "New client intake is a PDF form with 2-3 day manual processing lag", ai_intervention: "Conversational intake agent that qualifies, routes, and pre-populates case management system", codal_capability: "AI & Data", impact: "Medium" },
        { area: "Research", friction: "Legal research requires manual Westlaw queries and summarization", ai_intervention: "Internal RAG system over case database with citation-accurate synthesis", codal_capability: "AI & Data", impact: "High" },
      ],
    }),
  },
  {
    id: "8",
    status: "Passed",
    top_opportunity_tag: "Commerce Modernization",
    flagged_at: "2 days ago",
    brief: make({
      company_name: "Meridian Home Goods",
      url: "meridianhome-example.com",
      industry: "Retail & Consumer Goods",
      platform: "BigCommerce",
      platform_detail: "BigCommerce is a scalable foundation but the AR/visual and intent search layers are missing.",
      tech_stack_tags: ["BigCommerce", "React (PWA)"],
      ai_readiness_score: 58,
      ai_readiness_rationale: "Modern commerce platform with good extensibility; needs an AI experience layer.",
      llm_visibility_score: 27,
      llm_visibility_narrative: "Not surfacing in 'best home goods retailers' AI responses; Wayfair and West Elm dominate.",
      competitive_gaps: ["No room visualization/AR", "No semantic search", "No cart-recovery agent"],
      opportunity_tier: "S",
      opportunity_rationale: "Targeted feature engagement.",
      bd_opener: "BigCommerce gives you a scalable foundation, but your category pages and checkout are showing signals of friction that AI can address directly — particularly around room visualization and cross-sell. We're seeing 15–25% conversion lifts in home goods with AI room-preview features.",
      friction_opportunities: [
        { area: "Product Visualization", friction: "Static product images only; no room visualization or AR preview", ai_intervention: "AI-powered room visualization with style matching and complementary product suggestions", codal_capability: "Experience Design", impact: "High" },
        { area: "Search", friction: "Keyword-only search misses intent — 'cozy bedroom' returns no results", ai_intervention: "Semantic search with intent understanding and inspirational query support", codal_capability: "Unified Commerce", impact: "Medium" },
        { area: "Checkout", friction: "Multi-page checkout with high abandonment on shipping options step", ai_intervention: "AI-optimized checkout flow with predictive shipping selection and cart recovery agent", codal_capability: "Unified Commerce", impact: "Medium" },
      ],
    }),
  },
];
